when:
  - event: push
    branch: main

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands: 
      - touch ./TWN.DiscordBot.ControlPanel/appsettings.json
      - touch ./TWN.DiscordBot.Bot/appsettings.json
      - dotnet restore
      - dotnet build -c Release